# Generated by Django 2.1.2 on 2018-11-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camelot', '0003_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
