# Generated by Django 2.1.2 on 2018-12-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camelot', '0004_counter_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liuyan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('liuyan', models.CharField(max_length=2000)),
            ],
        ),
    ]
