# Generated by Django 2.1.2 on 2018-12-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camelot', '0006_product_shoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shopid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
