# Generated by Django 2.1.2 on 2018-12-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camelot', '0007_product_shopid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='jieshao',
            field=models.CharField(default='超好看', max_length=5000),
            preserve_default=False,
        ),
    ]
